### PR TITLE
platform: add Radxa ROCK 3C platform support

### PR DESCRIPTION
**Pull request by nascs**

### CODE REVIEW

**Comment by RadxaYuntian** [comment]
Documentation is missing.

**Review by RadxaYuntian — APPROVED** [review]

**Comment by RadxaYuntian** [comment]
@tingleby can you take a look at this?

**Comment by nascs** [comment]
@tingleby Can you take a look at this pr? I have tested it and it works!

**Review by tingleby — APPROVED** [review]

**Comment by tingleby** [comment]
Thanks for the contribution!

**Pull request merged**
