### PR TITLE
platform: add Radxa ROCK 5B platform support

### PR DESCRIPTION
**Pull request by nascs**

### CODE REVIEW

**Comment by nascs** [comment]
Hi @tingleby,  can you take a look at [pr 115](https://github.com/eclipse/mraa/pull/1115) and  this pr? For this pr, I have tested it and it works!

**Comment by nascs** [comment]
Hi @tingleby , I hope everything is going well. I really appreciate it that if you could take the time to help review this pr.

**Review by tingleby — APPROVED** [review]

**Comment by tingleby** [comment]
@nascs I tried to resovle the conflict in the Web UI and it seems to have screwed up. Can you please remove the merge commit I added the rebase the README.md changes.

**Comment by nascs** [comment]
> @nascs I tried to resovle the conflict in the Web UI and it seems to have screwed up. Can you please remove the merge commit I added the rebase the README.md changes.

Thanks for the reviewing, I've just dealt with the conflict.

**Comment by avalanche05** [comment]
I built the package. But, mraa-gpio cannot detect the Rock5B platform. 

`mraa-gpio version
Version v2.1.0-26-gd59936f on Unknown platform`

How can I fix it? @nascs

**Comment by nascs** [comment]
> I built the package. But, mraa-gpio cannot detect the Rock5B platform.
> 
> `mraa-gpio version Version v2.1.0-26-gd59936f on Unknown platform`
> 
> How can I fix it? @nascs

sorry for the later reply, What packages did you install? Please refer to [this document](https://wiki.radxa.com/Mraa#Install_example:_Install_Mraa_on_ROCK_Pi_4C_Debian_Bullseye_system) to install the relevant packages.

**Pull request merged**
