### PR TITLE
Detect RPi 4B Rev 1.2

### PR DESCRIPTION
**Pull request by windoze**
Signed-off-by Chen Xu (windoze@0d0a.com)

### CODE REVIEW

**Comment by windoze** [comment]
Don't know why but I'm unable to pass the ECA check, it says "This validation request is closed or unavailable.
".

**Comment by Propanu** [comment]
Hi @windoze, you'll have to sign up with Eclipse and accept the contributor agreement before you can start making contributions, please check https://www.eclipse.org/legal/ECA.php.

**Comment by windoze** [comment]
I've tried to follow the steps but in "My Profile" page it says
```
Detect RPi 4B Rev 1.2 #1013
This validation request is closed or unavailable.
```
And the PR# is also wrong, this one should be #1014 instead of 1013.

Don't know what happened.

**Comment by Chuckduey** [comment]
The revision codes for Raspberry Pi V1.2 Are a03112 for the 1GB, b03112 for the 2GB and c03112 for the 4GB version.  I suggest this PR gets amended by adding the other 2 V1.2 revision codes as well.  If there is still problems getting this PR going, I can create a PR with all the lasted revision codes according to the official Raspberry Pi documentation on their web site. [https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md](url)

**Comment by windoze** [comment]
Updated to detect 2GB version as well, but I still cannot pass the ECA check.
@Chuckduey maybe you can help to create another PR and drop this one.
Thanks.

**Comment by Chuckduey** [comment]
@windoze I created a new PR #1016 it added all the versions of V1.2 listed in the Raspberry Pi .org list.  I ran it on the latest NOOBS, and tested on several different versions of Pi.  Take a look at #1016 and see if it works for you.

**Comment by Propanu** [comment]
Hi, I merged #1016, please let me know if this can be closed.

**Comment by windoze** [comment]
It's now working properly on my RPi4B/4GB, thanks.

**Pull request closed without merging**
