### PR TITLE
platform: Add RISC-V architecture with VisionFive

### LINKED ISSUE #1097: RISC-V linux platform support
Hi, mraa team,
I try to build MRAA library in a RISCV LINUX platform, VisionFive board.
And it says, "Only x86, arm, mips, PERIPHERALMAN and mock platforms currently supported".

so When will MRAA support RISCV linux platform?

### PR DESCRIPTION
**Pull request by bovi**
Add RISC-V architecture and StarFive JH71x0-based boards VisionFive and VisionFive 2.

Signed-off-by: Daniel Bovensiepen
Signed-off-by: Zhu Jia Xing

FIX #1097

### CODE REVIEW

**Review by arfoll — APPROVED** [review]
Can't test it but looks good

**Comment by bovi** [comment]
Is there anything what still needs to be improved by us or can this be merged?

**Comment by bovi** [comment]
Could we merge here or is there anything we should still modify?

**Comment by bovi** [comment]
I updated the branch to resolve the conflict with the radxa merge. Can we merge here or is there anything you need else?

**Comment by bovi** [comment]
@tingleby we are celebrating here 1 year anniversary. Anything you would need us to do to merge this here?

**Review by arfoll — APPROVED** [review]

**Comment by bovi** [comment]
thanks @arfoll for the review!

**Comment by tingleby** [comment]
@bovi My apologies. Thanks @arfoll for the review too

**Comment by bovi** [comment]
> @bovi My apologies. Thanks @arfoll for the review too

no need to apologies. was just worried that there is something controversial in the merge request. thanks for the merge that helps us a lot to get rid of our internal patchsets! 🥰

**Pull request merged**
