### PR TITLE
include: Declare gVERSION global as 'extern'.

### PR DESCRIPTION
**Pull request by besser82**
Fixes build with '-fno-common'.

### CODE REVIEW

**Comment by Propanu** [comment]
@besser82, I have no issues merging this to the project but you need to sign the ECA. Let us know if you need help with that.

**Comment by ffontaine** [comment]
It should be noted that this PR is needed to fix the build with gcc 10 (which defaults to -fno-common)

**Comment by tingleby** [comment]
Cool @besser82 could you please take a look at the ECA check which we require to pull this.

**Comment by tingleby** [comment]
@besser82 Could you please create an Eclipse account to sign/ack the ECA. Id like to merge this patch. 
```
Before your contribution can be accepted by the project, you need to create and 
electronically sign the Eclipse Contributor Agreement (ECA) and sign 
off on the Eclipse Foundation Certificate of Origin. 

For more information, please visit

http://wiki.eclipse.org/Development_Resources/Contributing_via_Git
```

**Comment by jan-kiszka** [comment]
What's the status here? I'm also in need for fixing this (and did so locally before seeing this one).

**Comment by tingleby** [comment]
Merged, with aaa0a5cd4e401bde4fb3691dd4e6c70a5c61e031

**Pull request closed without merging**
